### ISSUE TITLE
Create UML for project layout

### ISSUE THREAD

**Issue by Tjzabel** [Tjzabel/csec-380-webapp#4]
*As a developer I would like to have documentation about how to implement the application*

Before we can start building out our application, we need to agree on a UML specification to follow. This includes:

* Use UML to describe user actions
* Design documentation availble in GitHub (via Wiki)
* Build mock page design and interaction

**Comment by Tjzabel** [comment]
@ncw0118 Use cases, flow graph 

@impos73r database schema, network topology, state diagram

**Comment by impos73r** [comment]
@impos73r 
- #7 
- #8 
- #9

**Comment by Tjzabel** [comment]
Done :+1:
