### ISSUE TITLE
Write Report for Act I

### ISSUE THREAD

**Issue by impos73r** [Tjzabel/csec-380-webapp#6]
Questions that need to be answered:
    • What is the URL of your Github project?
    • How did you breakup your projects and what are the security ramifications?
    • How did you choose to break down your Epic into various issues (tasks)?
    • How long did you assign each sprint to be?
    • Did you deviate from the Agile methodology at all? If yes, what is your reasoning for this?
    • How do you ensure that after each issue/milestone that security has been verified? How would you identify such issues in an ideal environment?

**Comment by impos73r** [comment]
@Tjzabel URL & Agile Methodology
@impos73r  Security Methodology
@ncw0118 & @Tjzabel  How did you breakup your projects and what are the security ramifications?

**Comment by impos73r** [comment]
Security Methodology done!

**Comment by ncw0118** [comment]
project breakup done

**Comment by Tjzabel** [comment]
Complete!
